export default [
  {
    brands: "Wix",
    description: "Contrary to popular belief, v",
    catogries: "",
    tags: "",
    nextMeeting: 1,
  },
  {
    brands: "Shopify",
    description:
      "Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
    members: "primis",
    catogries: "",
    tags: "",
    nextMeeting: 2,
  },
  {
    brands: "Mailchimp",
    description: "",
    members: "sapien",
    catogries: "semper",
    tags: "",
    nextMeeting: 3,
  },
  {
    brands: "Paypal",
    description: "Vivamus in felis eu sapien cursus vestibulum.",
    members: "vitae",
    catogries: "vestibulum",
    tags: "",
    nextMeeting: 4,
  },
  {
    brands: "Disney",
    description: "Nullam varius.",
    members: "",
    catogries: "ultricies",
    tags: "",
    nextMeeting: 5,
  },
  {
    brands: "Intercom",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla.",
    members: "",
    catogries: "",
    tags: "",
    nextMeeting: 6,
  },
  {
    brands: "Google",
    description: "",
    members: "",
    catogries: "",
    tags: "",
    nextMeeting: 7,
  },
  {
    brands: "Evernote",
    description: "",
    members: "",
    catogries: "sapien",
    tags: "",
    nextMeeting: 8,
  },
  {
    brands: "Microsoft",
    description: "",
    members: "",
    catogries: "fusce",
    tags: "",
    nextMeeting: 9,
  },
  {
    brands: "Invision",
    description: "Donec posuere metus vitae ipsum.",
    members: "nisl",
    catogries: "pulvinar",
    tags: "",
    nextMeeting: 10,
  },
];
